repos:
  - repo: local
    hooks:
      - id: check-pages-location
        name: Check pages location
        entry: bash scripts/precommit-check-pages.sh
        language: script
        stages: [commit]
